title: Marianna Carini # your name (or website title) here
logo: "/images/logo3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks), I am an analyst with 5+ years of experience as a Business Analyst. I have worked in the Aerospace and Sports industries. I recently obtained my MS in Business Analytics from the Paul Merage School of Business at the University of California, Irvine. I also hold a BS degree in Mathematics from California Polytechnic State University, San Luis Obispo. Through my work, I have developed a reputation for being a strategic thinker that is able to solve complex problems in an eloquent manner. Outside of work, I enjoy a variety of hobbies. I love all things DIY! My projects include everything from brewing my own kombucha to restoring vintage furniture. On a typical weekend, I can be found enjoying the outdoors with my dog Zeke, admiring a sunset, at a concert, and/or checking out a new local restaurant.
  
  <p align="center">
  <a href="pdf/resume2.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/marianna-carini/">LinkedIn</a> |
  <a href="https://github.com/m-carini">GitHub</a>
  </p>
  
  I am currently a Sr. Analyst at Disneyland with 5+ years of experience in the Entertainment, Aerospace, and Sports industries.
  <br><br>
  I have an MS degree in Business Analytics from UCI and BS in Mathematics from Cal Poly, SLO. I am passionate about solving complex problems in an eloquent manner!
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
